name             'blueleaf-chef'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures blueleaf-chef'
long_description 'Installs/Configures blueleaf-chef'
version          '0.1.0'
